# Generated by Django 4.0.1 on 2022-06-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_skill_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='static/img/Blank_Image.png', upload_to=''),
        ),
    ]
